//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP03Korsun.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int IdStudent { get; set; }
        public string LastNameStudent { get; set; }
        public string FirstNameStudent { get; set; }
        public string MiddleNameStudent { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string PassportSeria { get; set; }
        public string PassportNumber { get; set; }
        public int IdWhoGivePassport { get; set; }
        public System.DateTime DateWhoGivePassport { get; set; }
        public int IdPlaceOfBirth { get; set; }
        public int IdAddressRegistration { get; set; }
        public int IdGroup { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public string OMS { get; set; }
        public System.DateTime DateEducationStart { get; set; }
        public System.DateTime DateEducationEnd { get; set; }
        public int IdStatus { get; set; }
        public string OrderNumber { get; set; }
        public byte[] PhotoStudent { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Group Group { get; set; }
        public virtual Status Status { get; set; }
        public virtual WhoGivePassport WhoGivePassport { get; set; }
    }
}
